package pojo;

/**
 * Zoologicos generated by hbm2java
 */
public class Zoologicos implements java.io.Serializable {

	private int id;
	private String nombre;
	private String ciudad;
	private int anyoFundacion;

	public Zoologicos() {
	}

	public Zoologicos(int id, String nombre, String ciudad, int anyoFundacion) {
		this.id = id;
		this.nombre = nombre;
		this.ciudad = ciudad;
		this.anyoFundacion = anyoFundacion;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public int getAnyoFundacion() {
		return this.anyoFundacion;
	}

	public void setAnyoFundacion(int anyoFundacion) {
		this.anyoFundacion = anyoFundacion;
	}

}
